# Generated by Django 3.1 on 2020-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20201019_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='condition_for_getassured',
            field=models.BooleanField(default=False),
        ),
    ]
